# Generated by Django 6.1.1 on 2026-09-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_activity_icon_alter_category_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
