# Generated by Django 6.1.1 on 2026-09-25 19:19

import django.core.validators
import django.db.models.deletion
import places.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_place_views_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reviews/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), places.validators.validate_image_size])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.review')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
