# Generated by Django 6.1.1 on 2026-09-27 18:56

from django.db import migrations, models

from places.place_names import NAMES


def fill_names(apps, schema_editor):
    """Fills English and Tajik names of the seeded places that already exist."""
    Place = apps.get_model("places", "Place")
    for place in Place.objects.filter(name__in=NAMES):
        place.name_en, place.name_tg = NAMES[place.name]
        place.save(update_fields=["name_en", "name_tg"])


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='name_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='place',
            name='name_tg',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(fill_names, migrations.RunPython.noop),
    ]
