# Generated by Django 6.1.1 on 2026-09-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_place_name_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='placesuggestion',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='placesuggestion',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
